name: Branch - Stage V1

on:
  push:
    branches:
      - stage
  workflow_dispatch:

jobs:
  build-node:
    uses: ./.github/workflows/build-node.yml

    with:
      node_version: '22'
      app_env: 'stage'
      app_version: 'ci_${{ github.sha }}'
      azure_storage_account_name: ${{ vars.STAGE_AZURE_STORAGE_ACCOUNT_NAME }}
      azure_storage_container_name: ${{ vars.STAGE_AZURE_STORAGE_CONTAINER_NAME }}

    secrets:
      azure_storage_account_key: ${{ secrets.STAGE_AZURE_STORAGE_ACCOUNT_KEY }}

  build-canvas:
    needs: [build-node]
    uses: ./.github/workflows/build-canvas.yml
    with:
      node_version: '22'
      app_env: 'stage'
      app_version: 'ci_${{ github.sha }}'
      canvas_theme_js_file: 'https://st09417311stage-fybvhtameff0aney.z01.azurefd.net/themes/ci_${{ github.sha }}/theme-udirdesign.js'
      canvas_theme_css_file: 'https://st09417311stage-fybvhtameff0aney.z01.azurefd.net/themes/ci_${{ github.sha }}/theme-udirdesign.css'
      canvas_username: ${{ vars.STAGE_CANVAS_USERNAME }}

    secrets:
      canvas_password: ${{ secrets.STAGE_CANVAS_PASSWORD }}

  deploy-canvas:
    needs: [build-canvas]
    uses: ./.github/workflows/deploy-canvas.yml
    with:
      node_version: '22'
      app_env: 'stage'
      app_version: 'ci_${{ github.sha }}'
      canvas_username: ${{ vars.STAGE_CANVAS_USERNAME }}

    secrets:
      canvas_password: ${{ secrets.STAGE_CANVAS_PASSWORD }}
